all:
	sudo chmod u+s attack_server
	sudo chmod +x attack_server crack_attack
clean:
	sudo chmod -x attack_server
	sudo chmod -x crack_attack
	sudo chmod u-s attack_server
	rm attacker.h compression_virus
