drop table if exists "Combined_Records";
create table "Combined_Records"(
	"countrycode" character(3),
	"date" date,
	"regioncode" varchar(20),
	"jurisdiction" varchar(20),
	C1_combined_numeric float,
	C1_combined varchar(20),
	C2_combined_numeric float,
	C2_combined varchar(20),
	C3_combined_numeric float,
	C3_combined varchar(20),
	C4_combined_numeric float,
	C4_combined varchar(20),
	C5_combined_numeric float,
	C5_combined varchar(20),
	C6_combined_numeric float,
	C6_combined varchar(20),
	C7_combined_numeric float,
	C7_combined varchar(20),
	C8_combined_numeric float,
	C8_combined varchar(20),
	E1_combined_numeric float,
	E1_combined varchar(20),
	E2_combined_numeric float,
	E2_combined varchar(20),
	H1_combined_numeric float,
	H1_combined varchar(20),
	H2_combined_numeric float,
	H2_combined varchar(20),
	H3_combined_numeric float,
	H3_combined varchar(20),
	H6_combined_numeric float,
	H6_combined varchar(20),
	H7_combined_numeric float,
	H7_combined varchar(20),
	H8_combined_numeric float,
	H8_combined varchar(20),
	V1_combined_numeric float,
	V1_combined varchar(20),
	V2_combined_numeric float,
	V2_combined varchar(20),
	V3_combined_numeric float,
	V3_combined varchar(20),
	V4_combined_numeric float,
	V4_combined varchar(20)
);
insert into "Combined_Records"(
	"countrycode",
	"date",
	"regioncode",
	"jurisdiction",
	C1_combined_numeric,
	C1_combined,
	C2_combined_numeric,
	C2_combined,
	C3_combined_numeric,
	C3_combined,
	C4_combined_numeric,
	C4_combined,
	C5_combined_numeric,
	C5_combined,
	C6_combined_numeric,
	C6_combined,
	C7_combined_numeric,
	C7_combined,
	C8_combined_numeric,
	C8_combined,
	E1_combined_numeric,
	E1_combined,
	E2_combined_numeric,
	E2_combined,
	H1_combined_numeric,
	H1_combined,
	H2_combined_numeric,
	H2_combined,
	H3_combined_numeric,
	H3_combined,
	H6_combined_numeric,
	H6_combined,
	H7_combined_numeric,
	H7_combined,
	H8_combined_numeric,
	H8_combined,
	V1_combined_numeric,
	V1_combined,
	V2_combined_numeric,
	V2_combined,
	V3_combined_numeric,
	V3_combined,
	V4_combined_numeric,
	V4_combined
)
select "countrycode",
	"date",
	"regioncode",
	"jurisdiction",
	C1_combined_numeric,
	C1_combined,
	C2_combined_numeric,
	C2_combined,
	C3_combined_numeric,
	C3_combined,
	C4_combined_numeric,
	C4_combined,
	C5_combined_numeric,
	C5_combined,
	C6_combined_numeric,
	C6_combined,
	C7_combined_numeric,
	C7_combined,
	C8_combined_numeric,
	C8_combined,
	E1_combined_numeric,
	E1_combined,
	E2_combined_numeric,
	E2_combined,
	H1_combined_numeric,
	H1_combined,
	H2_combined_numeric,
	H2_combined,
	H3_combined_numeric,
	H3_combined,
	H6_combined_numeric,
	H6_combined,
	H7_combined_numeric,
	H7_combined,
	H8_combined_numeric,
	H8_combined,
	V1_combined_numeric,
	V1_combined,
	V2_combined_numeric,
	V2_combined,
	V3_combined_numeric,
	V3_combined,
	V4_combined_numeric,
	V4_combined
from "temporary"